language: ruby
dist: xenial
cache:
  bundler: true
  yarn: true
services:
- postgresql
- redis
branches:
  only:
  - main
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - chromium-chromedriver
    - google-chrome-stable
    - redis-server
env:
  global:
  - RAILS_ENV=test
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  >
  ./cc-test-reporter
- chmod +x ./cc-test-reporter
- export PATH=$PWD/geckodriver:$PATH
install:
- nvm install 10
- npm i -g yarn
- bundle install
- yarn install
before_script:
- cp example.env .env
- cp config/database.example.yml config/database.yml
- cp config/secrets.example.yml config/secrets.yml
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rails assets:precompile
script:
- bin/ci-run
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id
  $CC_TEST_REPORTER_ID"
deploy:
  provider: heroku
  cleanup: false
  on:
    repo: croissant-mfe/croissant
  app:
    main: croissant-tagging
  run:
  - bundle install
  - yarn install
  - bundle exec rake tmp:cache:clear
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
  - restart
  api_key:
    secure: quCt40xjVO45XD/hQ86RyOfQTsM6C8wZuk4+knZ2cotKpYggetMjoVo5GexFPyVduxLOpwdDwgJuLazASGeuz7ZzJ1GsmLQ20rJPcea1MaVWg2y9VGYrjKFYrP/bt2B/9EZlZihvCopKe3FY7F7TqamYzldBxfVos3UCsOwSYPBbZEegZ1b526TqsD0+a80TDgZ9sBBShn6+fWm5g7/Q2upUlhiGuho/HNx3I+P68rR6rAyuXSwQayycHfJpeJj7J8teZwIr51KUtAHjoAf9ypdXVMDnPvphkeaKaQMnr04IC/fKml4TUuT5gdMEVAamfAn30VbizMWIr5mOOToakRpJQ59fKeOpEbqOOVJCseJ6Pws60kPUgGIjcwm/nmQWa6lY7egP3nSCVz8g6huqKhEBkoz4EHV++jPgOZceIuWZALqhfPNjAU0EYLVCtw/+hYVwCw2WIwbR1pAXeoikBWIP7eBPLU5j/juX7imJ1Gu1LDYc6K6J9ecg6ypEC+IAkyZvkBcvHYP0eb3HrMtk4mEOK8ibNXNSlaQAV0kYY29QGhZhazqaE0/mLHjH6+wNjxvig0TeBUsbxDVesCLGb/9j9IeGv7NNnbLPcHaUostJIReIlRi1yRV7fZgLOt52/UK+PHhZHFZWm8NoDu4PtRIynVMDc5NNiN74BEizp48=
